pipeline{
    agent{
        docker{
            image 'python:3.7.2'
        }
    }
    stages{
        stage('build'){
            steps{
                echo 'check version and compiling app'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                    sh 'pip --version'
                }
            }
        }
        stage('test'){
            steps{
                echo 'test app'
                dir('vote'){
                    sh 'python3 app.py'
                }
            }
        }
    }
    post{
        always{
            echo 'Guntur Ananda Putra'
        }
    }
}