pipeline{
    agent{
        docker{
            image 'python:3.7.2'
            args '-u root:sudo -v $HOME/workspace/instavote_vote_vote_Jenkinsfile:/instavote_vote_vote_Jenkinsfile'
        }
    }
    stages{
        stage('build'){
            steps{
                echo 'check version and compiling app'
                dir('vote'){
                    sh 'pip3 install --no-cache-dir -r requirements.txt'
                }
            }
        }
        stage('test'){
            steps{
                echo 'test app'
                dir('vote'){
                    sh 'python3 --version'
                }
            }
        }
    }
    post{
        always{
            echo 'Guntur Ananda Putra'
        }
    }
}